<?php

/**
 * @file
 * Defines simple text field types.
 */

/**
 * Implements hook_help().
 */

function webspeech_stt_help($path, $arg) {
  switch ($path) {
    case 'admin/help#webspeech_stt':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t("The Webspeech SST module defines a text field that you can dictate text into using Chrome's implementation of the Webspeech API.  Use the correct field when editing your Content Type fields").'</p>';
      return $output;
  }
}

/**
 * Implements hook_field_info().
 *
 */

function webspeech_stt_field_info() {
  return array(    
    'webspeech_stt_long' => array(
      'label' => t('Webspeech STT Long text'),
      'description' => t('This field stores long text in the database.'),
      'instance_settings' => array('webspeech_stt_processing' => 0),
      'default_widget' => 'webspeech_stt_textarea',
      'default_formatter' => 'webspeech_stt_default',
    ),
  );
}

/**
 * Implements hook_field_settings_form().
 */

function webspeech_stt_field_settings_form($field, $instance, $has_data) {

  $settings = $field['settings'];

  $form = array();

  if ($field['type'] == 'webspeech_stt') {
    $form['max_length'] = array(
      '#type' => 'textfield',
      '#title' => t('Maximum length'),
      '#default_value' => $settings['max_length'],
      '#required' => TRUE,
      '#description' => t('The maximum length of the field in characters.'),
      '#element_validate' => array('element_validate_integer_positive'),
      // @todo: If $has_data, add a validate handler that only allows
      // max_length to increase.
      '#disabled' => $has_data,
    );
  }

  return $form;
}

/**
 * Implements hook_field_instance_settings_form().
 */
function webspeech_stt_field_instance_settings_form($field, $instance) {

  $settings = $instance['settings'];

  $form['webspeech_stt_processing'] = array(
    '#type' => 'radios',
    '#title' => t('Text processing'),
    '#default_value' => $settings['webspeech_stt_processing'],
    '#options' => array(
      t('Plain text'),
      t('Filtered text (user selects text format)'),
    ),
  );
  
  return $form;
}

/**
 * Implements hook_field_validate().
 *
 * Possible error codes:
 * - 'webspeech_stt_value_max_length': The value exceeds the maximum length.
 * - 'webspeech_stt_summary_max_length': The summary exceeds the maximum length.
 */

function webspeech_stt_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
  foreach ($items as $delta => $item) {
    // @todo Length is counted separately for summary and value, so the maximum
    //   length can be exceeded very easily.
    foreach (array('value', 'summary') as $column) {
      if (!empty($item[$column])) {
        if (!empty($field['settings']['max_length']) && drupal_strlen($item[$column]) > $field['settings']['max_length']) {
          switch ($column) {
            case 'value':
              $message = t('%name: the text may not be longer than %max characters.', array('%name' => $instance['label'], '%max' => $field['settings']['max_length']));
              break;

            case 'summary':
              $message = t('%name: the summary may not be longer than %max characters.', array('%name' => $instance['label'], '%max' => $field['settings']['max_length']));
              break;
          }
          $errors[$field['field_name']][$langcode][$delta][] = array(
            'error' => "webspeech_stt_{$column}_length",
            'message' => $message,
          );
        }
      }
    }
  }
}

/**
 * Implements hook_field_is_empty().
 */
function webspeech_stt_field_is_empty($item, $field) {
  if (!isset($item['value']) || $item['value'] === '') {
    return !isset($item['summary']) || $item['summary'] === '';
  }
  return FALSE;
}

/**
 * Implements hook_field_formatter_info().
 */
function webspeech_stt_field_formatter_info() {
  return array(
    'webspeech_stt_default' => array(
      'label' => t('Default'),
      'field types' => array('webspeech_stt', 'webspeech_stt_long'),
    ),
    'webspeech_stt_plain' => array(
      'label' => t('Plain text'),
      'field types' => array('webspeech_stt', 'webspeech_stt_long'),
    ),

    // The webspeech_stt_trimmed formatter displays the trimmed version of the
    // full element of the field. It is intended to be used with text
    // and webspeech_stt_long fields. It also works with webspeech_stt_with_summary
    // fields though the webspeech_stt_summary_or_trimmed formatter makes more
    // sense for that field type.
    'webspeech_stt_trimmed' => array(
      'label' => t('Trimmed'),
      'field types' => array('webspeech_stt', 'webspeech_stt_long'),
      'settings' => array('trim_length' => 600),
    ),

    // The 'summary or trimmed' field formatter for webspeech_stt_with_summary
    // fields displays returns the summary element of the field or, if
    // the summary is empty, the trimmed version of the full element
    // of the field.
    'webspeech_stt_summary_or_trimmed' => array(
      'label' => t('Summary or trimmed'),
      'field types' => array('webspeech_stt_with_summary'),
      'settings' => array('trim_length' => 600),
    ),
  );
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function webspeech_stt_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $element = array();

  if (strpos($display['type'], '_trimmed') !== FALSE) {
    $element['trim_length'] = array(
      '#title' => t('Trimmed limit'),
      '#type' => 'textfield',
      '#field_suffix' => t('characters'),
      '#size' => 10,
      '#default_value' => $settings['trim_length'],
      '#element_validate' => array('element_validate_integer_positive'),
      '#description' => t('If the summary is not set, the trimmed %label field will be shorter than this character limit.', array('%label' => $instance['label'])),
      '#required' => TRUE,
    );
  }

  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function webspeech_stt_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $summary = '';

  if (strpos($display['type'], '_trimmed') !== FALSE) {
    $summary = t('Trimmed limit: @trim_length characters', array('@trim_length' => $settings['trim_length']));
  }

  return $summary;
}

/**
 * Implements hook_field_formatter_view().
 */
function webspeech_stt_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  switch ($display['type']) {
    case 'webspeech_stt_default':
    case 'webspeech_stt_trimmed':
      foreach ($items as $delta => $item) {
        $output = _webspeech_stt_sanitize($instance, $langcode, $item, 'value');
        if ($display['type'] == 'webspeech_stt_trimmed') {
          $output = webspeech_stt_summary($output, $instance['settings']['webspeech_stt_processing'] ? $item['format'] : NULL, $display['settings']['trim_length']);
        }
        $element[$delta] = array('#markup' => $output);
      }
      break;

    case 'webspeech_stt_summary_or_trimmed':
      foreach ($items as $delta => $item) {
        if (!empty($item['summary'])) {
          $output = _webspeech_stt_sanitize($instance, $langcode, $item, 'summary');
        }
        else {
          $output = _webspeech_stt_sanitize($instance, $langcode, $item, 'value');
          $output = webspeech_stt_summary($output, $instance['settings']['webspeech_stt_processing'] ? $item['format'] : NULL, $display['settings']['trim_length']);
        }
        $element[$delta] = array('#markup' => $output);
      }
      break;

    case 'webspeech_stt_plain':
      foreach ($items as $delta => $item) {
        $element[$delta] = array('#markup' => strip_tags($item['value']));
      }
      break;
  }

  return $element;
}

/**
 * Sanitizes the 'value' or 'summary' data of a text value.
 *
 * Depending on whether the field instance uses text processing, data is run
 * through check_plain() or check_markup().
 *
 * @param $instance
 *   The instance definition.
 * @param $langcode
 *  The language associated to $item.
 * @param $item
 *   The field value to sanitize.
 * @param $column
 *   The column to sanitize (either 'value' or 'summary').
 *
 * @return
 *  The sanitized string.
 */
function _webspeech_stt_sanitize($instance, $langcode, $item, $column) {
  // If the value uses a cacheable text format, webspeech_stt_field_load() precomputes
  // the sanitized string.
  if (isset($item["safe_$column"])) {
    return $item["safe_$column"];
  }
  return $instance['settings']['webspeech_stt_processing'] ? check_markup($item[$column], $item['format'], $langcode) : check_plain($item[$column]);
}

/**
 * Generate a trimmed, formatted version of a text field value.
 *
 * If the end of the summary is not indicated using the <!--break--> delimiter
 * then we generate the summary automatically, trying to end it at a sensible
 * place such as the end of a paragraph, a line break, or the end of a
 * sentence (in that order of preference).
 *
 * @param $text
 *   The content for which a summary will be generated.
 * @param $format
 *   The format of the content.
 *   If the PHP filter is present and $text contains PHP code, we do not
 *   split it up to prevent parse errors.
 *   If the line break filter is present then we treat newlines embedded in
 *   $text as line breaks.
 *   If the htmlcorrector filter is present, it will be run on the generated
 *   summary (if different from the incoming $text).
 * @param $size
 *   The desired character length of the summary. If omitted, the default
 *   value will be used. Ignored if the special delimiter is present
 *   in $text.
 * @return
 *   The generated summary.
 */
function webspeech_stt_summary($text, $format = NULL, $size = NULL) {

  if (!isset($size)) {
    // What used to be called 'teaser' is now called 'summary', but
    // the variable 'teaser_length' is preserved for backwards compatibility.
    $size = variable_get('teaser_length', 600);
  }

  // Find where the delimiter is in the body
  $delimiter = strpos($text, '<!--break-->');

  // If the size is zero, and there is no delimiter, the entire body is the summary.
  if ($size == 0 && $delimiter === FALSE) {
    return $text;
  }

  // If a valid delimiter has been specified, use it to chop off the summary.
  if ($delimiter !== FALSE) {
    return substr($text, 0, $delimiter);
  }

  // We check for the presence of the PHP evaluator filter in the current
  // format. If the body contains PHP code, we do not split it up to prevent
  // parse errors.
  if (isset($format)) {
    $filters = filter_list_format($format);
    if (isset($filters['php_code']) && $filters['php_code']->status && strpos($text, '<?') !== FALSE) {
      return $text;
    }
  }

  // If we have a short body, the entire body is the summary.
  if (drupal_strlen($text) <= $size) {
    return $text;
  }

  // If the delimiter has not been specified, try to split at paragraph or
  // sentence boundaries.

  // The summary may not be longer than maximum length specified. Initial slice.
  $summary = truncate_utf8($text, $size);

  // Store the actual length of the UTF8 string -- which might not be the same
  // as $size.
  $max_rpos = strlen($summary);

  // How much to cut off the end of the summary so that it doesn't end in the
  // middle of a paragraph, sentence, or word.
  // Initialize it to maximum in order to find the minimum.
  $min_rpos = $max_rpos;

  // Store the reverse of the summary. We use strpos on the reversed needle and
  // haystack for speed and convenience.
  $reversed = strrev($summary);

  // Build an array of arrays of break points grouped by preference.
  $break_points = array();

  // A paragraph near the end of sliced summary is most preferable.
  $break_points[] = array('</p>' => 0);

  // If no complete paragraph then treat line breaks as paragraphs.
  $line_breaks = array('<br />' => 6, '<br>' => 4);
  // Newline only indicates a line break if line break converter
  // filter is present.
  if (isset($filters['filter_autop'])) {
    $line_breaks["\n"] = 1;
  }
  $break_points[] = $line_breaks;

  // If the first paragraph is too long, split at the end of a sentence.
  $break_points[] = array('. ' => 1, '! ' => 1, '? ' => 1, '。' => 0, '؟ ' => 1);

  // Iterate over the groups of break points until a break point is found.
  foreach ($break_points as $points) {
    // Look for each break point, starting at the end of the summary.
    foreach ($points as $point => $offset) {
      // The summary is already reversed, but the break point isn't.
      $rpos = strpos($reversed, strrev($point));
      if ($rpos !== FALSE) {
        $min_rpos = min($rpos + $offset, $min_rpos);
      }
    }

    // If a break point was found in this group, slice and stop searching.
    if ($min_rpos !== $max_rpos) {
      // Don't slice with length 0. Length must be <0 to slice from RHS.
      $summary = ($min_rpos === 0) ? $summary : substr($summary, 0, 0 - $min_rpos);
      break;
    }
  }

  // If the htmlcorrector filter is present, apply it to the generated summary.
  if (isset($filters['filter_htmlcorrector'])) {
    $summary = _filter_htmlcorrector($summary);
  }

  return $summary;
}

/**
 * Implements hook_field_widget_info().
 */
function webspeech_stt_field_widget_info() {
  return array(
    'webspeech_stt_textfield' => array(
      'label' => t('Webspeech STT Text field'),
      'field types' => array('webspeech_stt'),
      'settings' => array('size' => 60),
    ),
    'webspeech_stt_textarea' => array(
      'label' => t('Webspeech STT Text area (multiple rows)'),
      'field types' => array('webspeech_stt_long'),
      'settings' => array('rows' => 5),
    ),
  );
}

/**
 * Implements hook_field_widget_settings_form().
 */
function webspeech_stt_field_widget_settings_form($field, $instance) {
  $widget = $instance['widget'];
  $settings = $widget['settings'];

  if ($widget['type'] == 'webspeech_stt_textfield') {
    $form['size'] = array(
      '#type' => 'textfield',
      '#title' => t('Size of textfield'),
      '#default_value' => $settings['size'],
      '#required' => TRUE,
      '#element_validate' => array('element_validate_integer_positive'),
    );
  }
  else {
    $form['rows'] = array(
      '#type' => 'textfield',
      '#title' => t('Rows'),
      '#default_value' => $settings['rows'],
      '#required' => TRUE,
      '#element_validate' => array('element_validate_integer_positive'),
    );
  }

  return $form;
}

/**
 * Implements hook_field_widget_form().
 */
function webspeech_stt_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $summary_widget = array();
  $main_widget = array();
  //drupal_set_message("foo Drupal");
  //drupal_static_reset('sites/all/modules/webspeech_stt/webspeech_stt.js?v=1');
  // drupal_add_js('sites/all/modules/custom/webspeech_tts/webspeech_tts.js?v=1');


  switch ($instance['widget']['type']) {
    case 'webspeech_stt_textfield':
      $main_widget = $element + array(
        '#type' => 'textfield',
        '#default_value' => isset($items[$delta]['value']) ? $items[$delta]['value'] : NULL,
        '#size' => $instance['widget']['settings']['size'],
        '#maxlength' => $field['settings']['max_length'],
        '#attached' => array(
          'js' => array(drupal_get_path('module', 'webspeech_stt') . '/webspeech_stt.js'),
        ),
        '#attributes' => array('class' => array('text-full')),
        '#prefix' => '<div class="text-summary-wrapper" style="background-col"><button type="button" id="button_textfield">Record Speech</button>',
        '#id' => 'webspeech_stt_textfield',
      );
      break;

    
      // Fall through to the next case.

    case 'webspeech_stt_textarea':
      $main_widget = $element + array(
        '#type' => 'textarea',
        '#default_value' => isset($items[$delta]['value']) ? $items[$delta]['value'] : NULL,
        '#rows' => $instance['widget']['settings']['rows'],
        '#attributes' => array('class' => array('text-full')),
        '#id' => 'webspeech_stt_textarea',
        '#attached' => array(
          'js' => array(drupal_get_path('module', 'webspeech_stt') . '/webspeech_stt.js'),
        ),
        '#prefix' => '<div class="text-summary-wrapper"></div>',
        '#suffix' => '<button type="button" id="button_textarea">Record Speech </button></div>'
      );
      break;
  }

  if ($main_widget) {
    // Conditionally alter the form element's type if text processing is enabled.
    if ($instance['settings']['webspeech_stt_processing']) {
      $element = $main_widget;
      $element['#type'] = 'webspeech_stt_format';
      $element['#format'] = isset($items[$delta]['format']) ? $items[$delta]['format'] : NULL;
      $element['#base_type'] = $main_widget['#type'];
    }
    else {
      $element['value'] = $main_widget;
    }
  }
  if ($summary_widget) {
    $element['summary'] = $summary_widget;
  }

  return $element;
}

/**
 * Implements hook_field_widget_error().
 */
function webspeech_stt_field_widget_error($element, $error, $form, &$form_state) {
  switch ($error['error']) {
    case 'webspeech_stt_summary_max_length':
      $error_element = $element[$element['#columns'][1]];
      break;

    default:
      $error_element = $element[$element['#columns'][0]];
      break;
  }

  form_error($error_element, $error['message']);
}

/**
 * Implements hook_field_prepare_translation().
 */
function webspeech_stt_field_prepare_translation($entity_type, $entity, $field, $instance, $langcode, &$items, $source_entity, $source_langcode) {
  // If the translating user is not permitted to use the assigned text format,
  // we must not expose the source values.
  $field_name = $field['field_name'];
  if (!empty($source_entity->{$field_name}[$source_langcode])) {
    $formats = filter_formats();
    foreach ($source_entity->{$field_name}[$source_langcode] as $delta => $item) {
      $format_id = $item['format'];
      if (!empty($format_id) && !filter_access($formats[$format_id])) {
        unset($items[$delta]);
      }
    }
  }
}

/**
 * Implements hook_filter_format_update().
 */
function webspeech_stt_filter_format_update($format) {
  field_cache_clear();
}

/**
 * Implements hook_filter_format_disable().
 */
function webspeech_stt_filter_format_disable($format) {
  field_cache_clear();
}
